### ISSUE TITLE
Catchable fatal error: Instantiation of 'Closure' is not allowed in Luracast/Restler/Resources.php on line 711

### ISSUE THREAD

**Issue by swbullis** [Luracast/Restler#419] opened 2015-03-11 03:09 UTC
I'm getting this error when extending with EventDispatcher Class

Catchable fatal error: Instantiation of 'Closure' is not allowed in Luracast/Restler/Resources.php on line 711

```php
class IO extends EventDispatcher{

}
```
But after changing addListener from public to protected the error goes away.  

I'm not sure if this is a bug or just my particular use case nor am I sure this is a good fix.

**Comment by Arul-** [comment] 2015-03-17 07:55
Please provide us with the minimal code to reproduce this on RC6

**Comment by Arul-** [comment] 2015-05-25 09:36
I'm closing the issue as I could not reproduce. Please re-open with the sample code

**Closed by Arul-** 2015-05-25 09:36 UTC
Labels: R3, Unconfirmed
