### ISSUE TITLE
Explorer/Swagger issue & general customization questions

### ISSUE THREAD

**Issue by roynasser** [Luracast/Restler#610] opened 2018-10-10 17:04 UTC
Hi all,

I'm once again diving into some of the swagger features in Restler and have some issues... Is there some documentation or more full featured example about customizing the explorer features now that its builtin to restler?

I'm also having a weird behavior where as soon as explorer loads up all I get is this:

![image](https://user-images.githubusercontent.com/1218902/46752658-2ef78680-cc94-11e8-9199-034a5ec8cdfc.png)

swagger.json has loaded, and seems like valid json in the inspector...

![image](https://user-images.githubusercontent.com/1218902/46752755-66663300-cc94-11e8-9360-f30cd7981b57.png)
and I'm getting this which im not sure is related in the console...

![image](https://user-images.githubusercontent.com/1218902/46752797-80a01100-cc94-11e8-9594-226141e4449f.png)

Any idea about this or how to try to debug would be very helpful... googling hasnt really got me anywhere as of yet...

UPDATE: It seems despite being valid JSON, its an error in the swagger json causing a problem... I'm at a loss abt how to track it down though since there are so many methods :/

SyntaxError: Error resolving $ref pointer "/API/Explorer/swagger.json#/definitions/string". 
Token "string" does not exist.
    at Function.syntax (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:67:1507)
    at c.resolve (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:131266)
    at o.resolve (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:132605)
    at s._resolve (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:134856)
    at l (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:120926)
    at https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:120809
    at Array.forEach (<anonymous>)
    at a (https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:120731)
    at https://rebilly.github.io/ReDoc/redoc-demo.bundle.js:33:120828
    at Array.forEach (<anonymous>)

----------

Another issue which I'm foreseeing, is that I have implemented a customized secuirty layer that implements different user levels and permissions.  This all goes through an iAuthenticate class and validates different functions and classes through doccomments and user credentials as well as layers of security as well as what api calls are public, are internal, are available to apps or to end users, etc, and accorfding to permission levels, but this is all implementerd through __verifyAccess and __isAllowed functions, so in the end Restler is the one allowing or denying access... nonetheless despite having set Explorer to hide protected I see all endpoints in swagger.json... Is there somewhere I can look to understand better how it validates what classes are private/public etc? I guess I need to implement similar logic in case its not using the methods I stated above.

**Comment by Arul-** [comment] 2018-10-11 12:02
Are you using RC6?

**Comment by RVN-BR** [comment] 2018-10-11 12:16
We are pegged on this commit: https://github.com/Luracast/Restler/commit/dea5b92ee6f528cc61315db27fa9986b013ebf48

**Comment by Arul-** [comment] 2018-10-12 02:08
ReDoc looks nice and looks like I don't have to do much 👍

**Comment by Arul-** [comment] 2018-10-12 02:11
See https://github.com/Luracast/Restler/commit/9ca6dadb5f17e6dedccc3087957c8e2e25bd6cf8

We have a new way for explorer with multiple swagger spec support

**Comment by Arul-** [comment] 2018-10-12 02:15
## Support for both Swagger 1.2 and Swagger 2 and ability to choose either or both explorers

	$r->addAPIClass('Explorer1', 'explorer'); //swagger 1.2 spec
	$r->addAPIClass('Explorer2', 'explorer2'); //swagger 2 spec

You can always add

	$r->addAPIClass('Explorer'); //for latest swagger spec (currently 2)

**Comment by RVN-BR** [comment] 2018-10-15 12:59
That is what I'm using, but its generating some invalid JSON as per the first post? It seems its skipping a string proporty somewhere but I cant pinpoint where...

**Comment by Arul-** [comment] 2018-10-16 07:01
If you can pass me a simplified example to reproduce the issue, I can check and fix the issue

**Comment by Arul-** [comment] 2018-10-17 06:48
Just the swagger JSON may not be enough! Disable all `addAPI` calls and turn them on one by one until this issue appears. You can remove the body of all methods and pass the API class to me

**Comment by RVN-BR** [comment] 2018-10-31 21:34
Fonud it... One of our devs used {@type string} in one of the API definitions... Swagger didnt like that, but restler didnt mind... 

I removed it manually, but maybe you want to sanitize that in swagger...up to you...

**Comment by Arul-** [comment] 2018-11-01 15:35
I see

**Comment by RVN-BR** [comment] 2018-11-07 15:10
Found it! 👍 

Any (?) method which doesnt have a @param definition seems to be triggering this...

Previously having something such as below would work.  Currently it doesnt, and breaks the entire Explorer interface afaict... 

```
    /**
     *
     * @url GET /Param
     * @class xxxx\xxxxx\ication {@apiType front,apps,internal} {@expertPermission } {@appPermission ImpersonateExpert}
     * @protected
     */
    function Param($request_data = array()) {
```
having function Param($request_data = array()) or function Param($request_data) or function Param($var_a, $var_b) seems to be all the same.  Whenever no parameters are found for the function call, the generated model causes an error.

I was able to bypass this by adding a bogus parameter to all methods in a class such as @param string $var Placeholder... I did it to one class and it worked, but I cant do it for all my classes its just too much...

Since a lot of them use request_data and have the field names in the method description (not ideal for external doc I know, this is internal - still not ideal...i know) lol...

Anyways, thats the bug... Hope there is an easy fix, I have absolutely no idea abt the swagger code...

**Comment by Arul-** [comment] 2018-11-07 15:12
Ok, will check it out!

**Comment by roynasser** [comment] 2019-04-04 18:53
Has anyone had time to check this out?  If not, Arul do you have any idea for tackling this?  I might be able to look into it, but was wondering before I start looking at all changes to the comment parsing if you have any ideas

**Comment by Arul-** [comment] 2019-04-05 02:39
I'm working on the Explorer for Restler v4 now, so I will get it fixed along over the weekend

**Comment by roynasser** [comment] 2019-04-16 20:25
@Arul- will this be merged back into R3 or should I look at the reactive code to see what changed?

Thanks!

**Comment by Arul-** [comment] 2019-04-17 00:52
It will be released as restler 4 here! Till then you need to check the code base there

**Comment by Arul-** [comment] 2019-04-17 01:10
Once we fix the issue on v4, the same fix will be applied here as well!

**Comment by Arul-** [comment] 2021-07-19 06:35
This issue seems to be fixed in Restler 5 (formally RC6). Please re-open if required

**Closed by Arul-** 2021-07-19 06:35 UTC
